name: "CI (Integração Continua): Primeira Action"

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  jobs:
      exemplo: 
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@v3

        - name: Run a one-line script
            run: echo Hello world!